[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache"